# Generated by Django 3.0.1 on 2020-01-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_auto_20200108_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='restaurant',
        ),
    ]
