# Generated by Django 3.0.1 on 2020-01-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0008_auto_20200108_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='restaurant',
        ),
    ]
