# Generated by Django 3.0.1 on 2020-01-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0010_dish_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='restaurant',
        ),
    ]
