# Generated by Django 3.0.1 on 2020-01-05 15:05

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='cityarea', to='dishes.City')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('address', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='restaurant', to='dishes.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDishMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate', models.FloatField()),
                ('last_update', models.DateTimeField(default=datetime.datetime.now)),
                ('dish', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='userdishmatrix', to='dishes.Dish')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='userdishmatrix', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TagTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('col', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='col', to='dishes.Tag')),
                ('row', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='row', to='dishes.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='street', to='dishes.City')),
                ('city_area', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='street', to='dishes.CityArea')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dish', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='review', to='dishes.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='restauranttag', to='dishes.Restaurant')),
                ('tag', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='restauranttag', to='dishes.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='restaurantarea', to='dishes.CityArea')),
                ('restaurant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='restaurantarea', to='dishes.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('dish', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='rank', to='dishes.Dish')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='rank', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DistanceMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('col', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='col', to=settings.AUTH_USER_MODEL)),
                ('row', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='row', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DishTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='dishtag', to='dishes.Dish')),
                ('tag', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='dishtag', to='dishes.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='constraint', to='dishes.Tag')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='constraint', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='address', to='dishes.City'),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='address', to='dishes.Street'),
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='dish', to='dishes.Restaurant'),
        ),
    ]
