# Generated by Django 3.0 on 2020-01-11 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='RestaurantTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restauranttag', to='dishes.Restaurant')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restauranttag', to='dishes.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurantarea', to='dishes.CityArea')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurantarea', to='dishes.Restaurant')),
            ],
        ),
    ]
